### PR TITLE
add 4 bit benchmarks

### PR DESCRIPTION
**Pull request by wetdog**
I added additional benchmark with 4bit quant and bigger batching.

### CODE REVIEW

**Review by Vaibhavs10 — APPROVED** [review]
Thanks a lot for adding the benchmarks for 4-bit!

With some contributors, I'm making some changes to the CLI. So it might be worth re-basing to the main tomorrow and adding the benchmark then 🤗

**Comment by Vaibhavs10** [comment]
Hi @wetdog - do you mind re-basing and putting a list of benchmarks with whisper.cpp on CUDA.

**Comment by wetdog** [comment]
Sure Vb, I will update this weekend the benchmark with the rebase 🔥

**Comment by Vaibhavs10** [comment]
Perfect! I converted this to draft so that people there's no rush to merge!
Thanks again! <3

**Pull request closed without merging**
