### PR TITLE
Add timestamp parameter.

### PR DESCRIPTION
**Pull request by Vaibhavs10**
Still not sure of what is the best way to make this work.

### CODE REVIEW

**Comment by patrick91** [comment]
> Still not sure of what is the best way to make this work.

what do you mean?

**Comment by Vaibhavs10** [comment]
Oh the issue is that if in the `pipeline` you pass `return_timestamp=True` then it gives chunk by chunk timestamps.
However, you can also pass `return_timestamp='word'` which when passed gives you word level timestamps.


I don't want to duplicate code, so was thinking of the best way to have support this. I don't think `choices` supports different datatypes. 

Thoughts @patrick91

**Comment by patrick91** [comment]
you could use two flags, or just keep as it is nows, I think it's better to be explicit anyway

**Comment by search620** [comment]
The argument "return_timestamp='word'" does not work with Flash attention 2 and I have a real issue getting this word-level timing information.

Because the transcribe not take into account full sentences at stop etc... I need to use PunctuationModel + Spacy to do this correction on the final transcription. then I need to use word-level timestamps to merge all together to be more precise. but I can't get this word-level information which I really need to move forward. 

Any help would be greatly appreciated.

My end goal is to create SRT file to audio or a video for creating proper subtitles (which I already have the script ready)

**Pull request merged**
